### ISSUE TITLE
ReferenceError: client is not defined

### ISSUE THREAD

**Issue by danielantelo** [ziprandom/cucumberjs-json-api-mocking#3]
I'm using cucumberjs with cucumber-mink, now trying to add this to the works, but getting a client is not defined error.

```
const chromedriver = require('chromedriver');
const Mink = require('cucumber-mink');
const jsonApi = require('cucumberjs-json-api-mocking');

const parameters = {
  driver: {
    desiredCapabilities: {
      browserName: 'chrome',
    },
    port: 9515,
  },
};

module.exports = function minkInit() {
  jsonApi.call(this);
  chromedriver.start([
    '--url-base=/wd/hub',
  ]);
  Mink.init(this, parameters);
};

```

What can this be due to?

Thanks! Package looks great, hope i can get it working.

**Comment by ziprandom** [comment]
sorry for the late response to this. the steps where build using [webdriver](http://webdriver.io/) and assume the webdriver client/browser object is available as a variable named `client` in the step context. 

I can't test this now, but [here](http://mink.behat.org/en/latest/drivers/selenium.html#usage) is an example in which the variable get's named $client. so a simple 

```js
client = $client
```

should do the trick here..
